kind = "web"
previewPath = "/"
title = "LubisiaTeks Solutions"
version = "1.0.0"
id = "artifacts/lubisiateks"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20638

[services.development]
run = "pnpm --filter @workspace/lubisiateks run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lubisiateks", "run", "build" ]
publicDir = "artifacts/lubisiateks/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20638"
BASE_PATH = "/"
